### ISSUE TITLE
Zmienić nagłówki sekcji tak, by pasowały do plakatu

### ISSUE THREAD

**Issue by itabanita** [zwiazeksyndykalistowpolski/zsp-umowy-smieciowe#10]
![nagl](https://user-images.githubusercontent.com/15874828/41500697-08c71c76-7197-11e8-9e0c-80a734a663fa.jpg)
daj znac co sadzisz, to szybki przyklad tego o co mi chodzi

**Comment by blackandred** [comment]
Wstępnie jakoś mi to nie leży, ale źle też nie wygląda. Pewnie kwestia przyzwyczajnia do tego, co już widziałem. Na pewno musimy wtedy resztę sekcji dopasować.

**Comment by itabanita** [comment]
chodzi o to zeby laczylo sie z plakatem no. bo na razie to strona jest sliczna, wiadomo, ale nie ma zadnych punktow wspolnych wizualnie. zamiast losowego ksztaltu moge tez zrobic po prostu prostokat.

**Comment by itabanita** [comment]
zrobie wszystko na prostokacie, bedziesz mogl podstawic i sprawdzic czy ma to sens

**Comment by blackandred** [comment]
Ja tam grafiki raczej nie umieszczę, i tak będę to musiał raczej jakoś przerobić na CSS o ile będę potrafić :smile:

**Comment by blackandred** [comment]
Ostatecznie jak nie uda mi się wstawić tego jako czysty CSS to mogę wszystkie nagłówki w jednym pliku poprosić, wtedy z jednego pliku będę ładować.

**Comment by blackandred** [comment]
Trzeba wyslakować nagłówki tak aby na telefonach i tabletach się nie rozjeżdżały.
