### ISSUE TITLE
Możliwe błędy

### ISSUE THREAD

**Issue by lukandia** [zwiazeksyndykalistowpolski/zsp-umowy-smieciowe#15]
"Umowy cywilnoprawne typu umowa zlecenie oraz umowa o dzieło nie dają praktycznie żadnej ochrony w razie wypadku, choroby czy urodzenia dziecka." Jeśli strony się umówią, uprawnienia pracownicze w przypadku umowy cywilnoprawnej przysługują, tak np. w przypadku umowy zlecenie o ubezpieczeniu chorobowym decyduje zleceniobiorca.
"Płatne nadgodziny". W przypadku umów cywilnoprawnych nie istnieje pojęcie nadgodzin, więc trudno oczekiwać za nie wynagrodzenia.
„Jeżeli pracujesz na takiej umowie PRZECINEK zachęcamy Cię do zapoznania się z tym, jakie prawa przysługują (CI zamiast) Tobie na umowie o pracę.” LUB „Jeżeli pracujesz na takiej umowie PRZECINEK zachęcamy Cię do zapoznania z prawami, jakie przysługują Ci w przypadku o umowy o pracę.”
„Gdy pracodawca zwalnia Cię z powodu np. likwidacji stanowiska, gorszej sytuacji finansowej lub ogłoszenia upadłości PRZECINEK dostaniesz odszkodowanie pieniężne w postaci nawet do 3 wypłat. Gdyby firma upadła PRZECINEK możesz ubiegać się o wypłacenie zaległych wynagrodzeń z funduszu gwarantowanych świadczeń pracowniczych”
„W zależności od tego jak długo pracujesz PRZECINEK obowiązuje Cię okres wypowiedzenia, nie można Cię zwolnić z dnia na dzień. Oprócz tego PRZECINEK gdy na zakładzie pracy jest przynajmniej jeden związek zawodowy PRZECINEK pracodawca ma obowiązek zapytać związki przed zwolnieniem pracownika.”
„Koszt wynajmu 1ŁĄCZNIKpokojwego mieszkania we Wrocławiu”
„Koszt t-shirtu z nadrukiem w sklepie. PRZECIĘTNY KOSZT PRODUKCJI PODKOSZULKA WYNOSI 12 ZŁ. Zobacz PRZECINEK o ile Twój szef podbija cenę, a ile Tobie z tego daje - on sprowadza, Ty stoisz i sprzedajesz”
„Czy gdy zachorujesz na tydzień (bez „CZASU”) PRZECINEK będziesz w stanie zapłacić za czynsz i za życie?”
„Zakładając, że zarabiasz 1500 zł czy gdy bez urlopu chorobowego pracodawca odliczy 400 zł będzie Cię stać na wszystko?” – prawdopodobnie błędna składnia - wyjaśnij, proszę sens
„Czy będziesz w stanie przez jeden miesiąc noszenia gipsu nie płacić za mieszkanie PRZECINEK jeśli Twój pracodawca nie gwarantuje Tobie (proponuję CI zamiast „Tobie”) urlopu chorobowego?”
„Zła praca, złe warunki mieszkaniowe. Szef pewnie wynajmuje 2 albo 3 mieszkania i zgarnia po 1000 zł miesięcznie z każdego z nich PRZECINEK a Ciebie nie stać nawet na to aby mieć jedno (proponuję konsekwentnie „1”): aby mieszkać i płacić niski czynsz. Nie dość, że zarabiasz mało PRZECINEK to płacisz dużo na tych co mają więcej pieniędzy od Ciebie! To się nazywa wyzysk i klasizm.
„Bez okresu wypowiedzenia nie masz pewności PRZECINEK kiedy szef powie, że z dnia na dzień musisz zmienić pracę. Co (bez „WTEDY”) dasz dziecku do jedzenia w okresie poszukiwania pracy?”
"Szef pewnie wynajmuje 2 albo 3 mieszkania i zgarnia po 1000 zł miesięcznie z każdego z nich a Ciebie nie stać nawet na to aby mieć jedno: aby mieszkać i płacić niski czynsz. " Domniemanie o tym, że szef zarabia na wynajmie jest bezzasadne.

**Comment by blackandred** [comment]
Dziękuję

**Comment by blackandred** [comment]
1.
```
"Umowy cywilnoprawne typu umowa zlecenie oraz umowa o dzieło nie dają praktycznie żadnej ochrony w razie wypadku, choroby czy urodzenia dziecka." Jeśli strony się umówią, uprawnienia pracownicze w przypadku umowy cywilnoprawnej przysługują, tak np. w przypadku umowy zlecenie o ubezpieczeniu chorobowym decyduje zleceniobiorca.
```

Zgadzam się, można się ubezpieczyć dobrowolnie. I nie kosztuje to wcale dużo dla pracownika.
Zmienię to tak aby podkreślić, że prawnie pracownik nie jest chroniony. Umowa ustna pomiędzy pracownikiem a pracodawcą nie jest wystarczająca. Pracodawca zawsze może użyć swojej siły politycznej (faktu tego, że jest nad pracownikiem w hierarchii) aby zarządzić inaczej niż się umówił z pracownikiem.

**Comment by blackandred** [comment]
```
"Płatne nadgodziny". W przypadku umów cywilnoprawnych nie istnieje pojęcie nadgodzin, więc trudno oczekiwać za nie wynagrodzenia.
```

Ok, dodałem tą informację, zgadza się.

**Comment by blackandred** [comment]
```
„Jeżeli pracujesz na takiej umowie PRZECINEK zachęcamy Cię do zapoznania się z tym, jakie prawa przysługują (CI zamiast) Tobie na umowie o pracę.” LUB „Jeżeli pracujesz na takiej umowie PRZECINEK zachęcamy Cię do zapoznania z prawami, jakie przysługują Ci w przypadku o umowy o pracę.”
```

OK

**Comment by blackandred** [comment]
@blackandred a
