### ISSUE TITLE
do poprawy od Grazy

### ISSUE THREAD

**Issue by Graza16** [zwiazeksyndykalistowpolski/zsp-umowy-smieciowe#16]

**Comment by Graza16** [comment]
Trzeba poprawić pierwsze zdanie na stronie:
Jesteśmy organizacją non-profit, stworzyliśmy kampanię informacyjną, dzięki której dowiesz się, co Tobie przysługuje (nie jesteśmy organizacją non profit, a druga część zdania brzmi bardzo dziwnie)
Na:
Jesteśmy grupą non-profit, stworzyliśmy kampanię informacyjną, dzięki której dowiesz się, jakie przysługują Ci prawa

Fragment pod "Co mi przysługuje?"
"Umowy cywilnoprawne typu umowa zlecenie oraz umowa o dzieło nie dają prawnie wystarczającej ochrony w razie wypadku, choroby czy **nieplanowanej** ciąży". (usunąć "nieplanowanej". planowanie nie ma tutaj nic do rzeczy)

Macierzyństwo:
tu wszystko jest źle. Może przepisy się zmieniły? W kazdym razie powinno być tak:
"W związku z urodzeniem dziecka przysługuje Ci 20 tygodni urlopu macierzyńskiego – 6 tygodni możesz wykorzystać jeszcze przed porodem, a kolejne – po narodzinach dziecka. Urlop wynosi 100% podstawy wynagrodzenia.  Po upływie 14 tygodni mama może wrócić do pracy, pod warunkiem, że pozostałą część urlopu, czyli 6 tygodni wykorzysta tata dziecka (zatrudniony na podstawie umowy o pracę). Do tego przysługuje wam jeszcze urlop rodzicielski i bezpłatny wychowawczy"

**Comment by Graza16** [comment]
Teraz FAKTY:

1. Odnośniki do minimalnej krajowej są błędne. Nie rozumiem czemu jest podana strona o listonoszach i kelnerach. Powinna być np. ta: https://pl.wikipedia.org/wiki/P%C5%82aca_minimalna

2. 99%....
stawianie odnośników tylko do wyborczej i tylko o Solidarności to nie jest potwierdzenie tej tezy. moim zdaniem  nie da się jej wiarygodnie potwierdzić, lepiej usunąć
3. 35zł: (powinno być 43zł)
"koszt produkcji t-shirta" te dane dotyczą KOSZULI a nie t-shirta. Żródło tutaj: http://www.gazetaprawna.pl/artykuly/705719,tyle-naprawde-kosztuja-ubrania-za-65-groszy-koszule-uszyje-ci-dziecko-z-azji.html
4. 1 na 5
trzeba poprawić na 1 na 4
tu  żródło: https://www.rp.pl/Rynek-pracy/170809685-GUS-Polak-czesciej-pracuje-na-etacie.html

**Comment by blackandred** [comment]
Co do macierzyńskiego to są na pewno dwie opcje, a w zasadzie to jest to ciut bardziej złożone. Warto by było poruszyć to ogólnie z jakimś ewentualnie odnośnikiem. Istnieją na pewno dwie wysokości zasiłków, jedna 80% przez rok czasu, a druga to 100% i 60% za odpowiednio urlop macierzyński i rodzicielski.

**Comment by blackandred** [comment]
Odnośnie listonoszy i kelnerów to podciągnąłem to pod "najczęstsza wypłata w polsce".
Dodaję źródło z wikipedii, które podałaś oczywiście :)
