### ISSUE TITLE
Zmienić font w h1

### ISSUE THREAD

**Issue by itabanita** [zwiazeksyndykalistowpolski/zsp-umowy-smieciowe#8]

**Comment by blackandred** [comment]
Na jaki? :)

**Comment by itabanita** [comment]
moze League Gothic? https://www.theleagueofmoveabletype.com/league-gothic/?

**Comment by blackandred** [comment]
A jak z polskimi znakami w tym foncie?

**Comment by itabanita** [comment]
są polskie znaki

**Comment by blackandred** [comment]
@itabanita czy to zadanie jest wciąż aktualne?
